### ISSUE TITLE
Awesome but usability lacks

### ISSUE THREAD

**Issue by jcasement69** [PNNL-Comp-Mass-Spec/DB-Schema-Export-Tool#3]
While this solution looks loaded with all sorts of useful routines to export DB objects it really lacks the meat to get the simplest things done.  Like I just want to load the project and compile it and run it and get the views on the database exported.  On a scale of one to ten , it's a big fat zero.  Maybe if you are the author and you want others to look thru this entire solution and learn from it then fine.  But if you are like me and see a code which would help the whole entire SQL Devloper community but it fails to pass the sniff test then it's a fail as a shareable solution.  What's needed is simple and not a million switch settings that offer extreme flexibility.  You have to be able to download and run for people to adopt this code base.  Thanks for listening.

**Comment by alchemistmatt** [comment]
It is definitely true that this software includes a large number of features ... a result of [feature creep](https://en.wikipedia.org/wiki/Feature_creep) since it was first released in 2006 as a GUI, with the console app following in 2014.  My best advice would be to examine the `.conf` files in the Data and Automation directories, plus the `.bat` files in the Automation directory
* https://github.com/PNNL-Comp-Mass-Spec/DB-Schema-Export-Tool/tree/master/Data
* https://github.com/PNNL-Comp-Mass-Spec/DB-Schema-Export-Tool/tree/master/Automation
